version: "2"
services:
  tubesync:
    image: ghcr.io/meeb/tubesync:latest
    container_name: tubesync
    restart: unless-stopped
    ports:
      - 4848:4848
    volumes:
      - ~/Storage/Docker/tubesync/config:/config
      - ~/Storage/Tubesync/:/downloads
    environment:
      - TZ="America/Sao_Paulo"
      - PUID=1000
      - PGID=1000
    networks:
      - media

networks:
  media:
    name: media
    external: true