---
services:
  tubesync:
    image: ghcr.io/meeb/tubesync:latest
    container_name: tubesync
    restart: always
    labels:
      - io.portainer.accesscontrol.public
      - traefik.enable=true
      - traefik.http.routers.tubesync.rule=Host(`${PRIVATE_DOMAIN}`)
      - traefik.http.services.tubesync.loadbalancer.server.port=4848
    volumes:
      - /Storage/.Docker/Tubesync/config:/config
      - /Storage/Media/Tubesync:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - HTTP_USER=${HTTP_USER}
      - HTTP_PASS=${HTTP_PASS}
      - TUBESYNC_WORKERS=${TUBESYNC_WORKERS}
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - services

networks:
  services:
    name: services
    external: true