---
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /Storage/.Docker/sonarr/config:/config
      - /Storage/Media/tv-shows:/tv-shows
      - /Storage/Media/downloads/torrent:/data/complete/sonarr
    ports:
      - 8989:8989
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2048M
    networks:
      - services

networks:
  services:
    name: services
    external: true