---
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /Storage/.Docker/sonarr/config:/config
      - /Storage/Media/:/Storage/Media
    labels:
      - io.portainer.accesscontrol.public
      - traefik.enable=true
      - traefik.http.routers.sonarr.rule=Host(`${PRIVATE_DOMAIN}`)
      - traefik.http.services.sonarr.loadbalancer.server.port=8989
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2048M
    networks:
      - services

networks:
  services:
    name: services
    external: true