version: "3.8"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ~/Storage/Docker/sonarr/config:/config
      - ~/Storage:/storage
    ports:
      - 8989:8989
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - media

networks:
  media:
    name: media
    external: true