version: "2"
services:
  qbittorrent:
    image:  lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - GIDLIST=100
      - UMASK_SET=022
      - WEBUI_PORT=8080
    volumes:
      - '~/Storage/Docker/qbittorrent/config:/config'
      - '~/Storage/Downloads:/storage/'
    ports:
      - 6881:6881
      - 8080:8080
    restart: unless-stopped
    networks:
      - media

networks:
  media:
    name: media
    external: true