version: "3.8"
services:
  qbittorrent:
    image:  lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - GIDLIST=100
      - UMASK_SET=022
      - WEBUI_PORT=8080
    volumes:
      - '/Storage/.Docker/qbittorrent/config:/config'
      - '/Storage/Media:/storage/'
    ports:
      - 6881:6881
      - 8080:8080
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2048M
    networks:
      - media

networks:
  media:
    name: media
    external: true
