---
services:
  filebrowser:
    image: filebrowser/filebrowser
#    user: ${USER}
    container_name: filebrowser
    restart: unless-stopped
    volumes:
      - '/Storage/Public:/srv'
      - /Storage/.Docker/filebrowser/db:/database
      - /Storage/.Docker/filebrowser/config:/config
    environment:
      - PUID=1000
      - PGID=1000
    labels:
      - io.portainer.accesscontrol.public
      - traefik.enable=true
      - traefik.http.routers.filebrowser.rule=Host(`${PRIVATE_DOMAIN}`) || Host(`${PUBLIC_DOMAIN}`)
      - traefik.http.services.filebrowser.loadbalancer.server.port=80
    networks:
      - services

networks:
  services:
    name: services
    external: true
