---
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /Storage/.Docker/prowlarr/config:/config
    # ports:
    #   - 9696:9696
    labels:
      - io.portainer.accesscontrol.public
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - services

networks:
  services:
    name: services
    external: true