version: "2"
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ~/Storage/Docker/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
