services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000 
      - TZ=${TIME_ZONE}
      - SUBDOMAINS=${SUBDOMAINS}
      - TOKEN=${TOKEN}
      - UPDATE_IP=ipv4
      - LOG_FILE=false
    volumes:
      - /Storage/.Docker/duckdns/config:/config
    restart: unless-stopped
