version: "3.8"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "82:80"
    environment:
      TZ: 'America/Sao_Paulo'
      WEBPASSWORD: ${PIHOME_WEBPASSWORD}
      DNSMASQ_LISTENING : 'all'
      FTLCONF_LOCAL_IPV4: ${FTLCONF_LOCAL_IPV4}
      DNSMASQ_USER: root 
      PIHOLE_UID: 0
    volumes:
      - 'pi-hole:/etc/pihole'
      - 'pi-hole:/etc/dnsmasq.d'
    restart: unless-stopped
    networks:
      - services
    cap_add:
      - NET_ADMIN

volumes:
  pi-hole:

networks:
  services:
    name: services
    external: true