version: '3'
services:
  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    volumes:
      - '~/Storage/Public:/srv'
      - ~/Storage/Docker/filebrowser/db:/database
      - ~/Storage/Docker/filebrowser/config:/config
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 8095:80

networks:
  media:
    name: media
    external: true