version: '3'
services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    volumes:
      - '/Storage/Public:/srv'
      - /Storage/.Docker/filebrowser/db:/database
      - /Storage/.Docker/filebrowser/config:/config
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 80
    networks:
      - services

networks:
  services:
    name: services
    external: true