---
services:
  filebrowser:
    image: filebrowser/filebrowser
#    user: ${USER}
    container_name: filebrowser
    restart: unless-stopped
    volumes:
      - '/Storage/Public:/srv'
      - /Storage/.Docker/filebrowser/db:/database
      - /Storage/.Docker/filebrowser/config:/config
    environment:
      - PUID=1000
      - PGID=1000
    labels:
      - io.portainer.accesscontrol.public
    networks:
      - services

networks:
  services:
    name: services
    external: true
