---
version: '3.4'
services:
  linuxgsm-csgo:
    image: gameservermanagers/gameserver:csgo
    container_name: csgo-server
    volumes:
      - ~/Storage/Docker/steam/csgo:/data
    ports:
      - "27015:27015/tcp"
      - "27015:27015/udp"
      - "27020:27020/udp"
      - "27005:27005/udp"
    restart: unless-stopped
    user: $UID:$GID
    network_mode: "host"
    networks:
      - steam

networks:
  steam:
    name: steam
    external: true