---
version: '3.3'
services:
  jdownloader-2:
    container_name: jdownloader2
    ports:
      - '5800:5800'
    volumes:
      - '/Storage/.Docker/jdownloader2/config:/config:rw'
      - '/Storage/Media/downloads/http:/output:rw'
    image: jlesage/jdownloader-2
    deploy:
      resources:
        limits:
          memory: 1024M
    networks:
      - services

networks:
  services:
    name: services
    external: true