---
services:
  doplarr:
    image: lscr.io/linuxserver/doplarr:latest
    container_name: doplarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DISCORD__TOKEN=${DISCORD_TOKEN}
      # - OVERSEERR__API=${OVERSEERR_API}
      # - OVERSEERR__URL=http://${DOMAIN_URL}:5055
      - RADARR__API=${RADARR_API}
      - RADARR__URL=http://${DOMAIN_URL}:7878
      - SONARR__API=${SONARR_API}
      - SONARR__URL=http://${DOMAIN_URL}:8989
      - DISCORD__MAX_RESULTS=25 #optional
      # - DISCORD__REQUESTED_MSG_STYLE=:plain #optional
      # - SONARR__QUALITY_PROFILE= #optional
      # - RADARR__QUALITY_PROFILE= #optional
      # - SONARR__ROOTFOLDER= #optional
      # - RADARR__ROOTFOLDER= #optional
      # - SONARR__LANGUAGE_PROFILE= #optional
      # - OVERSEERR__DEFAULT_ID= #optional
      # - PARTIAL_SEASONS=true #optional
      # - LOG_LEVEL=:info #optional
      # - JAVA_OPTS= #optional
    # volumes:
    #   - /path/to/appdata/config:/config
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - media

networks:
  media:
    name: media
    external: true