---
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    ports:
      - 8200:8200
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - SETTINGS_ENCRYPTION_KEY=${SETTINGS_ENCRYPTION_KEY}
    volumes:
      - /Storage/.Docker/duplicati/config:/config
      - /Storage/Backups/Cloud:/backups
      - /Storage/Backups/immich:/backup/immich
      - /Storage/Backups/syncthing:/backup/syncthing
      - /Storage/Backups/proxmox:/backup/proxmox


    restart: unless-stopped
    networks:
      - services

networks:
  services:
    name: services
    external: true