---
services:
  speedtest-tracker:
    container_name: speedtest-tracker
    env_file:
      - .env
    volumes:
      - /Storage/.Docker/speedtest/config:/config
    image: lscr.io/linuxserver/speedtest-tracker:latest
    restart: unless-stopped
    labels:
      - io.portainer.accesscontrol.public
      - traefik.enable=true
      - traefik.http.routers.speedtest-tracker.rule=Host(`${PRIVATE_DOMAIN}`)
      - traefik.http.services.speedtest-tracker.loadbalancer.server.port=80
    depends_on:
      - speedtest_db
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - services
    
  speedtest_db:
    image: postgres:16-alpine
    container_name: speedtest-tracker-db
    labels:
      - io.portainer.accesscontrol.public
    restart: always
    env_file:
      - .env
    volumes:
        - db:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - services

volumes:
  db:

networks:
  services:
    name: services
    external: true

