---
services:
  speedtest-tracker:
    container_name: speedtest-tracker
    # ports:
    #   - 8080:80
    #   - 8443:443
    env_file:
      - .env
    volumes:
      - /Storage/.Docker/speedtest/config:/config
    image: lscr.io/linuxserver/speedtest-tracker:latest
    restart: unless-stopped
    labels:
      - io.portainer.accesscontrol.public
    depends_on:
      - speedtest_db
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - services
    
  speedtest_db:
    image: postgres:16-alpine
    container_name: speedtest-tracker-db
    labels:
      - io.portainer.accesscontrol.public
    restart: always
    env_file:
      - .env
    volumes:
        - db:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - services

volumes:
  db:

networks:
  services:
    name: services
    external: true

