---

services:
  speedtest-tracker:
    container_name: speedtest-tracker
    ports:
      - 8080:80
      - 8443:443
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - DB_CONNECTION=pgsql
      - APP_KEY=
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=${POSTGRES_DATABASE}
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - /Storage/.Docker/speedtest/config:/config
    image: lscr.io/linuxserver/speedtest-tracker:latest
    restart: unless-stopped
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - services
    
  db:
    image: postgres:16-alpine
    container_name: speedtest-tracker-db
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
        - speedtest_tracker_db:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - services

volumes:
  speedtest_tracker_db:

networks:
  services:
    name: services
    external: true

