---
services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - DB_CONNECTION=sqlite
    volumes:
      - speedtest-tracker:/config
    ports:
      - 8765:80
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - services

volumes:
  speedtest-tracker:

networks:
  services:
    name: services
    external: true

