---
services:
  app-speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker-app
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - DB_CONNECTION=pgsql
      - DB_HOST=db-speedtest-tracker
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${POSTGRES_DATABASE}
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - speedtest-tracker:/config
    ports:
      - 8765:80
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128M
    networks:
      - services

  db-speedtest-tracker:
    container_name: speedtest-tracker-db
    image: postgres:16-alpine
    restart: unless-stopped
    hostname: speedtest-tracker-db
    user: 1000:1000
    volumes:
      - speedtest-tracker-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - services

volumes:
  speedtest-tracker:
  speedtest-tracker-db:

networks:
  services:
    name: services
    external: true

