---
services:
  embyserver:
    image: lscr.io/linuxserver/emby:latest
    container_name: emby-server
    volumes:
      - '/Storage/.Docker/emby/data:/var/lib/emby'
      - '/Storage/.Docker/emby/config:/config'
      - '/Storage/Media:/Storage/Media'
    # ports:
    #   - 8096:8096
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4096M
    labels:
      - io.portainer.accesscontrol.public
    networks:
      - services

networks:
  services:
    name: services
    external: true