---
services:
  embyserver:
    image: lscr.io/linuxserver/emby:latest
    container_name: emby-server
    volumes:
      - '/Storage/.Docker/emby/data:/var/lib/emby'
      - '/Storage/.Docker/emby/config:/config'
      - '/Storage/Media:/Storage/Media'
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4096M
    labels:
      - io.portainer.accesscontrol.public
      - traefik.enable=true
      - traefik.http.routers.embyserver.rule=Host(`${PRIVATE_DOMAIN}`) || Host(`${PUBLIC_DOMAIN}`)
      - traefik.http.services.embyserver.loadbalancer.server.port=8096
    networks:
      - services

networks:
  services:
    name: services
    external: true