---
version: "3.8"
services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    container_name: nextcloud-aio
    restart: always
    ports:
      - 8081:80
    environment:
      - NEXTCLOUD_DATADIR="/mnt/nextcloud_data"
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /Storage/.Docker/nextcloud/data:/mnt/nextcloud/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - services

networks:
  services:
    name: services
    external: true

volumes:
  nextcloud_aio_mastercontainer: