---
version: "3.8"
services:
  nextcloud-db:
    image: mariadb
    restart: always
    container_name: nextcloud-mysql
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed

    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
    networks:
      - services

  nextcloud-app:
    image: nextcloud
    container_name: nextcloud-app
    restart: always
    ports:
      - 8081:80
    links:
      - nextcloud-db
    volumes:
      - ~/Storage/Docker/nextcloud-v2/files/:/var/www/html
    environment:
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_HOST=db
      - TZ="America/Sao_Paulo"
    networks:
      - services

networks:
  services:
    name: services
    external: true

volumes:
  nextcloud:
  db:
  