---
version: "3.8"
services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    container_name: nextcloud-aio
    restart: always
    ports:
      - 8081:80
    volumes:
      - /Storage/.Docker/nextcloud/data:/var/www/html
    networks:
      - services

networks:
  services:
    name: services
    external: true
