---
services:
  nextcloud_db:
    image: postgres:16-alpine
    container_name: nextcloud-db
    restart: always
    volumes:
      - nextcloud_db:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    labels:
      - io.portainer.accesscontrol.public
    networks:
      - services

  nextcloud_redis:
    image: redis:alpine
    container_name: nextcloud-redis
    labels:
      - io.portainer.accesscontrol.public
    restart: always
    networks:
      - services

  nextcloud_app:
    image: nextcloud:apache
    container_name: nextcloud-app
    restart: always
    ports:
      - 8080:80
    volumes:
      - /Storage/.Docker/nextcloud/data:/var/www/html:z
    environment:
      - POSTGRES_HOST=nextcloud_db
      - REDIS_HOST=nextcloud_redis
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    depends_on:
      - nextcloud_db
      - nextcloud_redis
    labels:
      - io.portainer.accesscontrol.public
    networks:
      - services

  nextcloud_cron:
    image: nextcloud:apache
    container_name: nextcloud-cron
    restart: always
    volumes:
      - /Storage/.Docker/nextcloud/data:/var/www/html:z
    entrypoint: /cron.sh
    depends_on:
      - nextcloud_db
      - nextcloud_redis
    labels:
      - io.portainer.accesscontrol.public
    networks:
      - services

networks:
  services:
    name: services
    external: true

volumes:
  nextcloud_db:
