---
version: "3.8"
services:

  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="America/Sao_Paulo"
      - POSTGRES_HOST=db_nextcloud
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER} 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db_nextcloud
    volumes:
      - ~/Storage/Docker/nextcloud2/user_data:/var/www/html
    ports:
      - 8443:80
    deploy:
      resources:
        limits:
          memory: 1024M
    restart: unless-stopped
    networks:
      - services
  
  db_nextcloud:
    container_name: nextcloud-db
    image: postgres:15-alpine
    restart: unless-stopped
    hostname: db_nextcloud
    user: 1000:1000
    volumes:
      - ~/Storage/Docker/nextcloud2/database/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - services

networks:
  services:
    name: services
    external: true