version: "3.8"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /Storage/.Docker/radarr/config:/config
      - /Storage/Media/movies:/movies
      - /Storage/Media/downloads/torrent/completed:/data
    ports:
      - 7878:7878
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2048M
    networks:
      - services

networks:
  services:
    name: services
    external: true
