---
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      PUID: 1000 
      PGID: 1000
    # ports:
    #   - 3000:3000
    volumes:
      - /Storage/.Docker/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1024M
    networks:
      - services

networks:
  services:
    name: services
    external: true