---
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      PUID: 1000 
      PGID: 1000
    env_file:
      - .env
    volumes:
      - /Storage/.Docker/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    dns:
      - ${CUSTOM_DNS_PROVIDER}
    labels:
      - io.portainer.accesscontrol.public
      - traefik.enable=true
      - traefik.http.routers.homepage.rule=Host(`${DOMAIN_NAME}`)
      - traefik.http.services.homepage.loadbalancer.server.port=3000
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - services

networks:
  services:
    name: services
    external: true