version: "3.8"
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="America/Sao_Paulo"
    volumes:
      - /Storage/.Docker/syncthing/config:/config
      - /Storage/Sync/${USER_01}:/data/${USER_01}
      - /Storage/Sync/${USER_02}:/data/${USER_02}
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
    networks:
      - services

networks:
  services:
    name: services
    external: true