version: "3.8"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "81:80"
    environment:
      TZ: 'America/Sao_Paulo'
      WEBPASSWORD: ${PIHOME_WEBPASSWORD}
      DNSMASQ_LISTENING : 'all'
    volumes:
      - '~/Storage/Docker/pihole/etc/pihole:/etc/pihole'
      - '~/Storage/Docker/pihole/etc/dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
    networks:
      - services

networks:
  services:
    name: services
    external: true