---
services:
  connector:
    environment:
      - TWINGATE_NETWORK=${TWINGATE_NETWORK}
      - TWINGATE_ACCESS_TOKEN=${TWINGATE_ACCESS_TOKEN}
      - TWINGATE_REFRESH_TOKEN=${TWINGATE_REFRESH_TOKEN}
      - TWINGATE_LABEL_HOSTNAME=${TWINGATE_LABEL_HOSTNAME}
      - TWINGATE_DNS=${TWINGATE_DNS}
      - TWINGATE_LOG_ANALYTICS=${TWINGATE_LOG_ANALYTICS}
      - TWINGATE_LABEL_DEPLOYED_BY=${TWINGATE_LABEL_DEPLOYED_BY}
    container_name: twingate
    restart: unless-stopped
    pull_policy: always
    labels:
      - io.portainer.accesscontrol.public
    image: twingate/connector:1
    networks:
      - services
networks:
  services:
    external: true