services:
  freetube:
    image: lscr.io/linuxserver/freetube:latest
    container_name: freetube
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /Storage/.Docker/freetube/config:/config
      - /Storage/Media/youtube:/downloads
    ports:
      - 3000:3000
      - 3001:3001
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1024M
    networks:
      - services

networks:
  services:
    name: services
    external: true
