version: "3.8"
services:
  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - ~/Storage/Docker/homer/assets/:/www/assets
    ports:
      - 80:8080
    user: 1000:1000
    environment:
      - INIT_ASSETS=0
      - PUID=1000
      - PGID=1000
      - TZ="America/Sao_Paulo"
    restart: unless-stopped
    networks:
      - services

networks:
  services:
    name: services
    external: true