---
services: 
  cloudflared: 
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel 
    restart: unless-stopped 
    command: tunnel --no-autoupdate run  
    environment: 
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}