---
services: 
  cloudflared: 
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel 
    labels:
      - io.portainer.accesscontrol.public
    restart: unless-stopped 
    command: tunnel --no-autoupdate run  
    environment: 
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - services

networks:
  services:
    name: services
    external: true