---
services:
  noip:
    image: ghcr.io/noipcom/noip-duc:latest
    container_name: noip
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    networks:
      - services

networks:
  services:
    name: services
    external: true