services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    container_name: stirling-pdf
    restart: unless-stopped

    # ports:
    #   - '8080:8080'
    labels:
      - io.portainer.accesscontrol.public
    volumes:
      - /Storage/.Docker/stirling/trainingData:/usr/share/tessdata #Required for extra OCR languages
      - /Storage/.Docker/stirling/configs:/configs
      - /Storage/.Docker/stirling/logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_GB
    deploy:
      resources:
        limits:
          memory: 2048M
    networks:
      - services

networks:
  services:
    name: services
    external: true