---
services:
  nextcloud_db:
    image: postgres:16-alpine
    container_name: nextcloud-db
    restart: always
    volumes:
      - nextcloud_db:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    labels:
      - io.portainer.accesscontrol.public
    networks:
      - services

  nextcloud_redis:
    image: redis:alpine
    container_name: nextcloud-redis
    labels:
      - io.portainer.accesscontrol.public
    restart: always
    networks:
      - services

  nextcloud_app:
    image: nextcloud:apache
    container_name: nextcloud-app
    restart: always
    volumes:
      - /Storage/.Docker/nextcloud/data:/var/www/html:z
    environment:
      - POSTGRES_HOST=nextcloud_db
      - REDIS_HOST=nextcloud_redis
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}
    depends_on:
      - nextcloud_db
      - nextcloud_redis
    labels:
      - io.portainer.accesscontrol.public
      - traefik.enable=true
      - traefik.http.routers.nextcloud_app.rule=Host(`${PRIVATE_DOMAIN}`) || Host(`${PUBLIC_DOMAIN}`)
      - traefik.http.services.nextcloud_app.loadbalancer.server.port=80
      # - traefik.http.routers.nextcloud.middlewares='nextcloud_redirectregex'
      # - traefik.http.middlewares.nextcloud_redirectregex.redirectregex.permanent=true
      # - traefik.http.middlewares.nextcloud_redirectregex.redirectregex.regex='https://(.*)/.well-known/(?:card|cal)dav'
      # - traefik.http.middlewares.nextcloud_redirectregex.redirectregex.replacement=https://$${1}/remote.php/dav'

    networks:
      - services

  nextcloud_cron:
    image: nextcloud:apache
    container_name: nextcloud-cron
    restart: always
    volumes:
      - /Storage/.Docker/nextcloud/data:/var/www/html:z
    entrypoint: /cron.sh
    depends_on:
      - nextcloud_db
      - nextcloud_redis
    labels:
      - io.portainer.accesscontrol.public
    networks:
      - services

networks:
  services:
    name: services
    external: true

volumes:
  nextcloud_db:
