
version: "2"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ~/Storage/Docker/jellyfin/config:/config
      - ~/Storage/Movies:/storage/movies/
      - ~/Storage/Tv-Shows:/storage/tv-shows/
    ports:
      - 8097:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp 
    restart: unless-stopped
    networks:
      - media

networks:
  media:
    name: media
    external: true