version: '3.8'
services:
  gitlab-server:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab-server
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url ${GITLAB_URL}
        nginx['listen_port'] = ${GITLAB_PORT}
        gitlab_rails['initial_root_password'] = ${GITLAB_ROOT_PASSWORD}
        puma['worker_processes'] = 0
    volumes:
      - ~/Storage/.Docker/gitlab/server/config:/etc/gitlab
      - ~/Storage/.Docker/gitlab/server/logs:/var/log/gitlab
      - ~/Storage/.Docker/gitlab/server/data:/var/opt/gitlab
    ports:
      - '8088:8088'

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - gitlab-server
  