version: "3.8"
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /Storage/.Docker/bazarr/config:/config
      - /Storage/Media/Tv-Shows:/storage/tv-shows
      - /Storage/Media/Movies:/storage/movies
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      - media

networks:
  media:
    name: media
    external: true