---
services:
  uptime-kuma:
    restart: always
    container_name: uptime-kuma
    image: 'louislam/uptime-kuma:latest'
    volumes:
      - /Storage/.Docker/uptime-kuma/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      - PUID=1000
      - PGID=1000
    labels:
      - io.portainer.accesscontrol.public
      - traefik.enable=true
      - traefik.http.routers.uptime-kuma.rule=Host(`${PRIVATE_DOMAIN}`)
      - traefik.http.services.uptime-kuma.loadbalancer.server.port=3001
    networks:
      - services

networks:
  services:
    name: services
    external: true