---
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /Storage/.Docker/bazarr/config:/config
      - /Storage/Media/tv-shows:/Storage/Media/tv-shows
      - /Storage/Media/movies:/Storage/Media/movies
    labels:
      - io.portainer.accesscontrol.public
      - traefik.enable=true
      - traefik.http.routers.bazarr.rule=Host(`${DOMAIN_NAME}`)
      - traefik.http.services.bazarr.loadbalancer.server.port=6767
    restart: unless-stopped
    networks:
      - services

networks:
  services:
    name: services
    external: true