version: '3.3'
services:
  rust-server:
    container_name: rust-server
    ports:
     - '28015:28015'
     - '28015:28015/udp'
     - '28016:28016'
     - '8081:8080'
    environment:
     - RUST_SERVER_NAME=${RUST_SERVER_NAME}
     - RUST_SERVER_WORLDSIZE=${RUST_SERVER_WORLDSIZE}
     - RUST_RCON_PASSWORD=${RUST_RCON_PASSWORD}
     - RUST_OXIDE_ENABLED=${RUST_OXIDE_ENABLED}
    volumes:
     - '~/.docker-storage/game-server/rust:/steamcmd/rust'
    image: didstopia/rust-server