services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    env_file:
      - .env
    # ports:
    #   - "8081:8081"
    volumes:
      - /Storage/Media/metube:/downloads
      - /Storage/.Docker/metube/config:/app/config
    networks:
      - services

networks:
  services:
    name: services
    external: true