services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    environment:
      - UID=1000
      - GID=1000
      - DEFAULT_THEME=dark
      - AUDIO_DOWNLOAD_DIR=/downloads/audio
      - URL_PREFIX='http://yt.matfor.local'
    # ports:
    #   - "8081:8081"
    volumes:
      - /Storage/Media/youtube:/downloads
    networks:
      - services

networks:
  services:
    name: services
    external: true