---
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - USER=${USER}
      - PASS=${PASS}
      - WHITELIST=${WHITELIST}
    volumes:
      - /Storage/.Docker/transmission/data:/config
      - /Storage/Media/downloads/torrent/completed:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2048M
    networks:
      - services

networks:
  services:
    name: services
    external: true