---
title: "ZION"
subtitle: "Services"
logo: "logo.png"

header: false
footer: false

stylesheet:
  - "assets/custom.css"

columns: "3"
theme: default
colors:
  light:
    highlight-primary: "#fff5f2"
    highlight-secondary: "#fff5f2"
    highlight-hover: "#bebebe"
    background: "#12152B"
    card-background: "rgba(255, 245, 242, 0.8)"
    text: "#ffffff"
    text-header: "#fafafa"
    text-title: "#000000"
    text-subtitle: "#111111"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#3273dc"
    link-hover: "#2e4053"
    background-image: "../assets/wallpaper-light.jpeg" # Change wallpaper.jpeg to the name of your own custom wallpaper!
  dark:
    highlight-primary: "#181C3A"
    highlight-secondary: "#181C3A"
    highlight-hover: "#1F2347"
    background: "#12152B"
    card-background: "rgba(24, 28, 58, 0.8)"
    text: "#eaeaea"
    text-header: "#7C71DD"
    text-title: "#fafafa"
    text-subtitle: "#8B8D9C"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#c1c1c1"
    link-hover: "#fafafa"
    background-image: "../assets/wallpaper.jpeg"

services:
  - name: "Services"
    items:
      - name: "Emby"
        logo: "assets/icons/png/emby.png" 
        tag: "SAFE"
        tagstyle: "is-success" 
        url: "http://192.168.3.12:8096/"
        target: "_blank"

      - name: "Nextcloud"
        logo: "assets/icons/png/nextcloud.png" 
        tag: "SAFE"
        tagstyle: "is-success" 
        url: "http://192.168.3.12:8443/"
        target: "_blank"

      - name: "Jellyseerr"
        logo: "assets/icons/png/jellyseerr.png" 
        tag: "SAFE"
        tagstyle: "is-success" 
        url: "http://192.168.3.12:5055/"
        target: "_blank"
      
      - name: "Jellyfin"
        logo: "assets/icons/png/jellyfin.png" 
        tag: "SAFE"
        tagstyle: "is-success" 
        url: "http://192.168.3.12:8097/"
        target: "_blank"

  - name: "Bots"
    items:
      - name: "qBittorrent"
        logo: "assets/icons/png/qbittorrent.png"
        tag: "DANGEROUS!"
        tagstyle: "is-danger" 
        url: "http://192.168.3.12:8080/"
        target: "_blank"

      - name: "Radarr"
        logo: "assets/icons/png/radarr.png" 
        tag: "DANGEROUS!"
        tagstyle: "is-danger" 
        url: "http://192.168.3.12:7878/"
        target: "_blank"

      - name: "Sonarr"
        logo: "assets/icons/png/sonarr.png" 
        tag: "DANGEROUS!"
        tagstyle: "is-danger" 
        url: "http://192.168.3.12:8989/"
        target: "_blank"

      - name: "Prowlarr"
        logo: "assets/icons/png/prowlarr.png" 
        tag: "DANGEROUS!"
        tagstyle: "is-danger" 
        url: "http://192.168.3.12:9696/"
        target: "_blank"

      - name: "Bazarr"
        logo: "assets/icons/png/bazarr.png" 
        tag: "DANGEROUS!"
        tagstyle: "is-danger" 
        url: "http://192.168.3.12:6767/"
        target: "_blank"
      
      - name: "TubeSync"
        logo: "assets/icons/png/youtube.png" 
        tag: "DANGEROUS!"
        tagstyle: "is-danger" 
        url: "http://192.168.3.12:4848/"
        target: "_blank"

      - name: "Notifiarr"
        logo: "assets/icons/png/notifiarr.png" 
        tag: "DANGEROUS!"
        tagstyle: "is-danger" 
        url: "http://192.168.3.12:5454/"
        target: "_blank"

  - name: "Admin"
    items:
      - name: "Cockpit"
        logo: "assets/icons/png/cockpit.png" 
        tag: "DANGEROUS!"
        tagstyle: "is-danger" 
        url: "http://192.168.3.12:9090/"
        target: "_blank"

      - name: "PiHole"
        logo: "assets/icons/png/pihole.png" 
        tag: "DANGEROUS!"
        tagstyle: "is-danger" 
        url: "http://192.168.3.12:81/"
        target: "_blank"

      - name: "Portainer"
        logo: "assets/icons/png/portainer.png" 
        tag: "DANGEROUS!"
        tagstyle: "is-danger" 
        url: "http://192.168.3.12:9000/"
        target: "_blank"

      - name: "pgAdmin"
        logo: "assets/icons/png/pgadmin.png" 
        tag: "Production"
        tagstyle: "is-danger" 
        url: "http://192.168.3.12:16543/"
        target: "_blank"

      - name: "SpeedTest"
        logo: "assets/icons/png/airsonic.png" 
        tag: "Production"
        tagstyle: "is-danger" 
        url: "http://192.168.3.12:8765/"
        target: "_blank"

      - name: "Kuma"
        logo: "assets/icons/png/uptime-kuma.png" 
        tag: "Production"
        tagstyle: "is-danger" 
        url: "http://192.168.3.12:3001/"
        target: "_blank"