---
services:
  uptime-kuma:
    restart: always
    ports:
      - '3001:3001'
    container_name: uptime-kuma
    image: 'louislam/uptime-kuma:latest'
    volumes:
      - /Storage/.Docker/uptime-kuma/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      - PUID=1000
      - PGID=1000
    labels:
      - io.portainer.accesscontrol.public
    networks:
      - services

networks:
  services:
    name: services
    external: true