version: '3.3'
services:
  uptime-kuma:
    restart: always
    ports:
      - '3001:3001'
    container_name: uptime-kuma
    image: 'louislam/uptime-kuma:1'
    networks:
      - services

networks:
  services:
    name: services
    external: true