version: '3.3'
services:
  uptime-kuma:
    restart: always
    ports:
        - '3001:3001'
    volumes:
        - '~/Storage/Docker/uptime-kuma/data:/app/data'
    container_name: uptime-kuma
    image: 'louislam/uptime-kuma:1'