---
services:
  npm-app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: proxy-manager
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    environment:
      PUID: 1000
      PGID: 1000
      DB_MYSQL_HOST: "npm-db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: ${MYSQL_USER}
      DB_MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DB_MYSQL_NAME: ${MYSQL_DATABASE}
      DISABLE_IPV6: 'true'
    volumes:
      - /Storage/.Docker/nginx-proxy-manager/app/data:/data
      - /Storage/.Docker/nginx-proxy-manager/app/letsencrypt:/etc/letsencrypt
    depends_on:
      - npm-db
    networks:
      - services

  npm-db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    container_name: proxy-manager-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MARIADB_AUTO_UPGRADE: '1'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - services

networks:
  services:
    name: services
    external: true

volumes:
  db_data: