---
services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /Storage/.Docker/lidarr/config:/config
      - /Storage/Media/:/Storage/Media
      - /Storage/Media/downloads/complete
    labels:
      - io.portainer.accesscontrol.public
      - traefik.enable=true
      - traefik.http.routers.lidarr.rule=Host(`${PRIVATE_DOMAIN}`)
      - traefik.http.services.lidarr.loadbalancer.server.port=8686
    deploy:
      resources:
        limits:
          memory: 2048M
    networks:
      - services
    restart: unless-stopped

networks:
  services:
    name: services
    external: true