services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /Storage/Media/metube:/downloads
      - /Storage/.Docker/metube/config:/app/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.metube.rule=Host(`${DOMAIN_NAME}`)
      - traefik.http.services.metube.loadbalancer.server.port=8081
    networks:
      - services

networks:
  services:
    name: services
    external: true