FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends \
    bash \
    zip \
    cron \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
ENV CRON_SCHEDULE="0 6 * * 1"
COPY compress_and_encrypt.sh /usr/local/bin/compress_and_encrypt
RUN chmod +x /usr/local/bin/compress_and_encrypt
RUN echo "$CRON_SCHEDULE /usr/local/bin/compress_and_encrypt >> /var/log/cron.log 2>&1" >> /etc/crontab
CMD ["cron", "-f"]
