---
services:
  compress:
    build:
      context: .
      dockerfile: Dockerfile.cron
    image: compress_encrypt
    user: root
    container_name: compress-and-encrypt
    environment:
      - COMPRESS_PASSWORD=${COMPRESS_PASSWORD}   # Optional
      - CRON_SCHEDULE="0 6 * * 1"
    labels:
      - io.portainer.accesscontrol.public
    volumes:
      - /Storage/.Docker/nextcloud/data/data/cristiane/files:/input_dir/cristiane
      - /Storage/.Docker/nextcloud/data/data/admin/files:/input_dir/admin
      - /Storage/Backups/cloud:/output_dir