---
services:
  compress:
    build:
      context: .
      dockerfile: Dockerfile
    image: compress_encrypt
    user: root
    container_name: compress-and-encrypt
    environment:
      - COMPRESS_PASSWORD=${COMPRESS_PASSWORD}   # Optional
      - CRON_SCHEDULE="0 6 * * 1"
    labels:
      - io.portainer.accesscontrol.public
    volumes:
      - /Storage/.Docker/nextcloud/data/data/admin/files:/input_dir/admin
      - /Storage/.Docker/nextcloud/data/data/${USER_PROFILE_01}/files:/input_dir/${USER_PROFILE_01}
      - /Storage/Backups/Companies:/input_dir/companies
      - /Storage/Backups/Cloud:/output_dir
    network_mode: "host"        
