version: "3.8"
services:
  steam-zomboid:
    image: gameservermanagers/gameserver:pz
    container_name: zomboid
    restart: unless-stopped
    volumes:
      - ~/Storage/Docker/steam/zomboid:/data
    user: $UID:$GID
    ports:
      - 16261:16261/udp
      - 16261:16261/tcp
      - 16262:16262/udp
      - 16262:16262/tcp
    networks:
      - steam

networks:
  steam:
    name: steam
    external: true