---
services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - TZ=America/Sao_Paulo
      - JELLYFIN_TYPE=emby
    volumes:
      - /Storage/.Docker/jellyseerr/config:/app/config
      - /Storage/Media:/Storage/Media
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - services
    labels:
      - io.portainer.accesscontrol.public
      - traefik.enable=true
      - traefik.http.routers.jellyseerr.rule=Host(`${PRIVATE_DOMAIN}`) || Host(`${PRIVATE_DOMAIN2}`) || Host(`${PUBLIC_DOMAIN}`)
      - traefik.http.services.jellyseerr.loadbalancer.server.port=5055
      
networks:
  services:
    name: services
    external: true