version: "3.8"
services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Sao_Paulo
    ports:
      - 5055:5055
    volumes:
      - ~/Storage/Docker/jellyseerr/config:/app/config
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - media

networks:
  media:
    name: media
    external: true